# Generated by Django 5.2.4 on 2025-12-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Published',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_create_APT_repositories', 'Can create published APT_repositories'), ('can_edit_APT_repositories', 'Can edit published APT_repositories'), ('can_delete_APT_repositories', 'Can delete published APT_repositories')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_create_repos', 'Can create repositories'), ('can_edit_repos', 'Can edit repositories'), ('can_delete_repos', 'Can delete repositories'), ('can_upload_repos', 'Can upload packages to repository'), ('can_remove_repos', 'Can remove packages from repository')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_create_snapshots', 'Can create snapshots'), ('can_edit_snapshots', 'Can edit snapshots'), ('can_delete_snapshots', 'Can delete snapshots')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
